version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: wingobank
      POSTGRES_PASSWORD: wingobank
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

volumes:
  pgdata:
